defaultSemverRangePrefix: ''

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.1.cjs

injectEnvironmentFiles: ['.env.yarn']

npmScopes:
  '1schoolone':
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_PAT}
    npmRegistryServer: 'https://npm.pkg.github.com'
