services:
  schoolmarks-client:
    build:
      context: .
    container_name: schoolmarks-client
    restart: always
    ports:
      - '8080:8080'
    environment:
      - GITHUB_PAT=${GITHUB_PAT}
      - VITE_API_HOST=${VITE_API_HOST}
