name: Health

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

env:
  GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
  NODE_VERSION: '20.17.0'

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo GITHUB_PAT=${{ env.GITHUB_PAT }} >> .env

      - name: NPM Audit
        run: yarn npm audit

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo GITHUB_PAT=${{ env.GITHUB_PAT }} >> .env

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo GITHUB_PAT=${{ env.GITHUB_PAT }} >> .env

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Vitest
        run: yarn test
