name: Health

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

env:
  GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
  NODE_VERSION: '20.17.0'

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo GITHUB_PAT=${{ env.GITHUB_PAT }} >> .env.yarn

      - name: NPM Audit
        run: yarn npm audit

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo GITHUB_PAT=${{ env.GITHUB_PAT }} >> .env.yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo GITHUB_PAT=${{ env.GITHUB_PAT }} >> .env.yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Vitest
        run: yarn test

      - name: Setup Pages
        if: github.ref == 'refs/heads/develop'
        uses: actions/configure-pages@v3

      - name: Upload Report Artifact
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-pages-artifact@v3
        with:
          name: vitest-report
          path: '.vitest-report/'

  publish:
    name: Publish reports
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      pages: write
      id-token: write
    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: GH Pages deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: vitest-report
