name: Publish and Deploy

on:
  workflow_run:
    workflows: ['Health']
    branches:
      - main
    types:
      - completed

env:
  REGISTRY: registry.ilhanyapici.com
  IMAGE_NAME: schoolmarks/client

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login
        run: |
          docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Publish
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
