name: Code Style

permissions:
  pull-requests: write

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

env:
  GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
  NODE_VERSION: '20.17.0'

jobs:
  format:
    name: Format (Prettier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo GITHUB_PAT=${{ env.GITHUB_PAT }} >> .env.yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check Formatting
        run: yarn format

  lint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo GITHUB_PAT=${{ env.GITHUB_PAT }} >> .env.yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Check Linting
        run: yarn run lint:report

      - name: Upload Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint_report
          path: eslint_report.json

  lint-annotation:
    name: Lint Annotation
    # Only run on pull requests, when the lint job has failed
    if: github.event_name == 'pull_request' && failure()
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: eslint_report

      - uses: ataylorme/eslint-annotate-action@v3
        with:
          report-json: 'eslint_report.json'
